services:
  tms:
    image: "pshannon/tms"
    ports:
      - "8888:8787"
      - "15000-15010:15000-15010"
    environment:
       PASSWORD: password
       DISABLE_AUTH: true
    volumes:
       - tms_data:/home/rstudio/stage
  ghdb:
    image: "pshannon/ghdb"
    environment:
      POSTGRES_PASSWORD: trena
      PGDATA: /var/lib/postgresql/data/pgdata
volumes:
  tms_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/paul/github/TrenaMultiScore/docker/stage
      
      
    
